name: Code Verification

on:
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.17.0
      - name: Run tests
        run: sbt test

  lint:
    runs-on:
      labels: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.17.0
      - name: Check licenses
        run: sbt licenseCheck
      - name: Lint code
        run: sbt scalafmtCheckAll scalafmtSbtCheck
